# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/0469f40a-edb2-4e73-af8b-965db36314b6";
    fsType = "btrfs";
    options = [ 
      "subvol=@root"
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/home" ={
    device = "/dev/disk/by-uuid/0469f40a-edb2-4e73-af8b-965db36314b6";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:3"
      "noatime"
     ];
  };

  fileSystems."/nix" = { 
    device = "/dev/disk/by-uuid/0469f40a-edb2-4e73-af8b-965db36314b6";
    fsType = "btrfs";
    options = [ 
      "subvol=@nix"
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/E032-65E3";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/efi" = { 
    device = "/dev/disk/by-uuid/FCED-98D2";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
