{ lib, ... }:

let
  lua = lib.generators.mkLuaInline;

  mkBind = key: action: {
    _args = [
      key
      (lua action)
    ];
  };

  appBinds = [
    (mkBind "SUPER + T" ''
      hl.dsp.exec_cmd("kitty")
    '')
  ];

  windowBinds = [
    (mkBind "SUPER + X" ''
      hl.dsp.window.close()
    '')
  ];

  startupHooks = [
    {
      _args = [
        "hyprland.start"
        (lua ''
          function()
            hl.exec_cmd("noctalia")
          end
        '')
      ];
    }
  ];

in {
  wayland.windowManager.hyprland = {
    enable = true;
    package = null;
    configType = "lua";

    settings = {
      config = {
        autogenerated = false;
      };

      bind =
        appBinds
        ++ windowBinds;

      on = startupHooks;
    };
  };

  xdg.portal = {
    enable = true;

    config.hyprland = {
      default = [
        "hyprland"
	"gtk"
      ];
    };
  };
}
